# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MENU_interfaz1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import *

from PySide6.QtGui import *

from PySide6.QtWidgets import *




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QRect(30, 160, 231, 51))
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QRect(30, 230, 231, 51))
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QRect(30, 300, 231, 51))
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QRect(30, 370, 231, 51))
        self.horizontalSlider_4.setOrientation(Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(280, 180, 47, 14))
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QRect(280, 250, 47, 14))
        self.label_2.setObjectName("label_2")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QRect(280, 320, 47, 14))
        self.label_3.setObjectName("label_3")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setGeometry(QRect(280, 390, 47, 14))
        self.label_4.setObjectName("label_4")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QRect(341, 250, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QRect(470, 250, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QRect(330, 170, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QRect(490, 170, 201, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QRect(340, 320, 311, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        
        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)
        #self.serial_port = None


    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "P1"))
        self.label_2.setText(_translate("MainWindow", "P2"))
        self.label_3.setText(_translate("MainWindow", "P3"))
        self.label_4.setText(_translate("MainWindow", "P4"))
        self.comboBox.setItemText(0, _translate("MainWindow", "COM0"))
        self.comboBox.setItemText(1, _translate("MainWindow", "COM1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "COM2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "COM3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "COM4"))
        self.comboBox.setItemText(5, _translate("MainWindow", "COM5"))
        self.comboBox.setItemText(6, _translate("MainWindow", "COM6"))
        self.comboBox.setItemText(7, _translate("MainWindow", "COM7"))
        self.comboBox.setItemText(8, _translate("MainWindow", "COM8"))
        self.comboBox.setItemText(9, _translate("MainWindow", "COM9"))
        self.comboBox.setItemText(10, _translate("MainWindow", "COM10"))
        self.comboBox.setItemText(11, _translate("MainWindow", "COM11"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "MANUAL"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "EEPROM"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "SERIAL"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "ADAFRUIT"))
        self.pushButton.setText(_translate("MainWindow", "CONECTAR"))
        self.pushButton_2.setText(_translate("MainWindow", "DESCONECTAR"))
        self.pushButton_3.setText(_translate("MainWindow", "SELECCIONAR MODO"))
